Algoritmo "Calcular área de um trapézio"

Var


BaseMaior, BaseMenor, H :  inteiro
area : real


Inicio


// ENTRADA

Escreval("Informe a Base Maior: ")
leia(BaseMaior)

Escreval("Informe a Base Menor")
leia(BaseMenor)

Escreval("Informe a Altura")
leia(H)

//PROCESSAMENTO

area <- ((BaseMaior + BaseMenor) / 2) * H


//Saída

Escreval("O valor da área do trapézio será de: ", area)


Fimalgoritmo