Algoritmo "OPERADORES RELACIONAIS"

Var

x   : real

result, result2, result3, result4, result5, result6 : logico


Inicio

//ENTRADA

Escreval("Informe um número: ")
leia(x)

//PROCESSAMENTO

result <- x = x

result2 <- x > x

result3 <- x < x

result4  <- x >= x

result5  <- x  >= x

result6 <- x <> x



//SAÍDA

Escreval(result)
Escreval(result2)
Escreval(result3)
Escreval(result4)
Escreval(result5)
Escreval(result6)




Fimalgoritmo