Algoritmo "Par ou ímpar"

Var

   x : inteiro
   
   //Não utilizamos o tipo real


Inicio

   //Escrever um programa que verifique e informe se um número inteiro qualquer digitado é par ou ímpar


   //ENTRADA

   Escreval("Informe o número")
   leia(x)


   se (x MOD 2 = 0) entao
      Escreval("O número ", x," é par")
   senao
      Escreval("O número ", x," é ímpar")

   fimse


Fimalgoritmo